### ISSUE TITLE
Support table rows

### ISSUE THREAD

**Issue by elmcrest** [pornel/slip#23]
Hi kornel,

first of all, congratz to slip.js - works really nice.

I was wondering though if there's a way to make table rows (bootstrap 3 table-responsive in particular) drag & droppable, too?

Sorry if I'm wrong starting this as an "issue" since I guess it isn't one. But I don't know where to ask here else.

thx in advance,
elmcrest

But the way, so far I've found this http://jsfiddle.net/martyk/Kzf62/85/ which should work with touch punch on mobile, too.

**Comment by carter-thaxton** [comment]
Confirmed that attaching to `tbody` works.
