### ISSUE TITLE
Autoscrolling issue when html/body set to 100%

### ISSUE THREAD

**Issue by guillerodriguez** [pornel/slip#28]
I am seeing issues with autoscrolling when the height of the html and body elements is set to 100% (so that the body fills the whole viewport). I have fixed this by modifying `updatePosition()` to include `scrollable.scrollTop` in the calculation of `bottomOffset`:

    bottomOffset = Math.min(scrollable.scrollTop + containerRect.bottom, window.innerHeight) - targetRect.bottom,

This seems to fix the problem.

Does this look correct?

**Comment by henrikhermansen** [comment]
I had issues with scrolling on mobile, the page kept skipping up and down. Substituting this line seems to have fixed it. Thanks!

**Comment by guillerodriguez** [comment]
@henrikhermansen -- thank you for letting me know. I am also using this myself with good results.

**Comment by carter-thaxton** [comment]
I believe these issues were fixed in #72.  Please feel free to reopen if you discover otherwise.
