### ISSUE TITLE
Page height grows when dragging item beyond page bottom

### ISSUE THREAD

**Issue by guillerodriguez** [pornel/slip#29]
When testing on desktop browsers (Chrome, FF) I found that trying to drag an item beyond the bottom of the page quickly makes the page height grow out of control (the page height will keep growing as long as you keep dragging the item beyond the page bottom). This can be seen in the live demo at http://pornel.net/slip

The following fix in `updatePosition()` avoids this problem:

            if (bottomOffset < triggerOffset){
            	offset = triggerOffset - bottomOffset;

            	// Don't apply offset if it would scroll beyond the end of the page
            	var rootEl = document.documentElement,
            		bodyEl = document.body,
            		scrollTop = (rootEl && rootEl.scrollTop) || bodyEl.scrollTop,
            		scrollHeight = (rootEl && rootEl.scrollHeight) || bodyEl.scrollHeight;
            		
            	if ((scrollTop + window.innerHeight + offset) >= scrollHeight) {
            		offset = 0;
            	}
            }
            else if (topOffset < triggerOffset){
                offset = topOffset - triggerOffset;
            }

**Comment by carter-thaxton** [comment]
I believe these issues were fixed in #71 and #72.  Please feel free to reopen if you find additional issues.
