### ISSUE TITLE
Bug when scrolling on Mobile Safari IOS 8.1

### ISSUE THREAD

**Issue by lirbank** [pornel/slip#32]
Heya,

Found this small bug when implementing and it's also present in your example https://pornel.net/slip/ - so should be easy to reproduce. If you scroll the list on IOS it will output the error seen in the screenshot many times. You have to scroll the list buy touching the list itself (if you scroll by grabbing on the page footer for example, then the error won't appear). Also does NOT happen on desktop browsers (including Safari).

Totally love your lib!

The screenshots:

![image](https://cloud.githubusercontent.com/assets/2538130/5152196/32dbf42c-71a1-11e4-8d48-1b1e7fdffe97.png)

![image](https://cloud.githubusercontent.com/assets/2538130/5152201/3f038d78-71a1-11e4-85a2-39815ebd0bfa.png)

**Comment by mauron85** [comment]
I can confirm that bug in Chrome for Android and also in Chrome Desktop when emulating touch events.
