### ISSUE TITLE
Broken in Webkit on mac - removeMouseHandlers called straight after first mouse move

### ISSUE THREAD

**Issue by madeinspace** [pornel/slip#46]
Only happens in Chrome and Safari on Mac. Only happens once on load. As soon as you start dragging the event handlers are removed.

Chrome Version 43.0.2357.10 dev (64-bit) still in beta. Last known version with no issue is Chrome 41.0.2272.118

**Comment by carter-thaxton** [comment]
I'm not seeing this issue anymore.  It may have been fixed in the last year.  Please feel free to reopen if you still see it occur.
