### ISSUE TITLE
Animation lag after ipad unlock

### ISSUE THREAD

**Issue by senner007** [pornel/slip#47]

**Comment by pornel** [comment]
Yeah, sorry. It's likely an iOS issue.

**Comment by senner007** [comment]
This solves it for my projects:

*{
 -webkit-transform: translate3d(0, 0, 0);
   -moz-transform: translate3d(0, 0, 0);
   -ms-transform: translate3d(0, 0, 0);
   transform: translate3d(0, 0, 0);  
}

Although, doing this might have an impact on load or memory. Don't know.

**Comment by pornel** [comment]
This is a very bad idea — it will disable hardware acceleration (when too many elements are layers browsers give up and fall back to CPU rendering).

**Comment by senner007** [comment]
It works fine for me. It definately uses hardware acceleration and the animation smoothness is as good as it can ever get.
