### ISSUE TITLE
Cannot read property 'scrollContainer' of null

### ISSUE THREAD

**Issue by simpzan** [pornel/slip#48]
when use it on chrome Mac version with iPhone mode, the console prints out the following error:
```
Uncaught TypeError: Cannot read property 'scrollContainer' of null   slip.js:634
window.Slip.Slip.updatePosition                                                          slip.js:634
window.Slip.Slip.onTouchMove                                                           slip.js:672
```

**Comment by ptbrowne** [comment]
+1

**Comment by callumbrown-spartan** [comment]
This problem seems to have been fixed in https://github.com/pornel/slip/commit/1524fdfd772c4ddbdb02c5b56b64a2188430ff35 but it wasn't in the slip.js file that I got when doing a bower install.
