### ISSUE TITLE
Item being dragged not going on top of other items in Chrome 43

### ISSUE THREAD

**Issue by humphreybc** [pornel/slip#49]
It appears Chrome 43 has changed something which now causes the item that's being reordered to sit "behind" the other items in the list as it's dragged up or down. This is best demonstrated in action:

Firefox 38.05 or Chrome < 43:

![slip-ff](https://cloud.githubusercontent.com/assets/1124253/8018331/5eb21bae-0c5a-11e5-8dbd-cd2b1518cb7e.gif)

Chrome 43:

![slip-chrome-43](https://cloud.githubusercontent.com/assets/1124253/8018332/652f96be-0c5a-11e5-85bf-1f9532982f4d.gif)

**Comment by salcott** [comment]
Having the same problem in cordova

**Comment by humphreybc** [comment]
This might be relevant: http://stackoverflow.com/questions/29611680/chrome-incorrect-z-axis-order-with-translate3d

**Comment by humphreybc** [comment]
Not 100% sure, but it looks like it could be this bug in Chrome:
https://code.google.com/p/chromium/issues/detail?id=565089

**Comment by carter-thaxton** [comment]
Confirmed that this occurs in Chrome 43.  I've added `position: relative` to the list items in the example, and some documentation to recommend adding something similar for projects that use Slip.
