### ISSUE TITLE
Odd jump if I only move an item down one spot

### ISSUE THREAD

**Issue by jorjordandan** [pornel/slip#54]
Hi - this is a great library, so first off, thanks!

I'm using Slip to add reordering to [meteoric] (https://github.com/meteoric/meteor-ionic), the meteor port of the ionic framework, but I have a small glitch. When I move an item down only one spot, it animates up at the last second, after I let go. You can [see the issue here] (https://github.com/meteoric/meteor-ionic) (click the upper right-hand corner to enable re-ordering).

The [implementation is here] (https://github.com/jorjordandan/meteor-ionic/blob/master/components/ionList/ionList.js).

I noticed your demo doesn't have this issue, so I understand this is probably an implementation issue, but if someone could give me a hint about where to start looking, I'd definitely appreciate it.

**Comment by jorjordandan** [comment]
Oddly enough, if I comment out [this line](https://github.com/pornel/slip/blob/master/slip.js#L744) of Slip.js there is no issue. What else does this line affect?

**Comment by pornel** [comment]
This line is supposed to animate move of the element back to its original position.

**Comment by pornel** [comment]
when you reorder, call `preventDefault` to prevent that animation.
