### ISSUE TITLE
List item 'bounces' as it moves into new position, when reordering list with latest slip.js

### ISSUE THREAD

**Issue by mgorczyca** [pornel/slip#63]
On 1/26/16, I downloaded the most recent version of slip.js. When reordering my list, the list item being moved did not go into its new position smoothly. Instead, there was a 'bounce' of about 50px. This behavior did not occur when using the demo at https://kornel.ski/slip/. I downloaded the slip.js code being used in the demo, used that version in my project, and the 'bouncing' behavior no longer occurred. I can use the older slip.js for my needs, but wanted to let you know about this issue.

**Comment by carter-thaxton** [comment]
I believe this was fixed by #72.
