### ISSUE TITLE
What is the utility of this.target.node.style.willChange?

### ISSUE THREAD

**Issue by Jenselme** [pornel/slip#66]
This was introduced in https://github.com/pornel/slip/commit/9649fe050e6c5a56b6adece932940401d2225549 and I don't see what it is used for.

However, we found [a bug](https://github.com/geoadmin/mf-geoadmin3/issues/3197) in an application that uses slijps but if I comment [this line](https://github.com/pornel/slip/blob/master/slip.js#L239) it works.

Should it be removed or if it has an interest, should [transformPrefix](https://github.com/pornel/slip/blob/master/slip.js#L133) and [transformProperty](https://github.com/pornel/slip/blob/master/slip.js#L134) be improved?

**Comment by pornel** [comment]
Setting willChange informs the browser that the element will animate soon, so it should be using an accelerated layer. Without it you would have a delay/jerky animation when it starts moving.

Setting transformProperty to an empty string like that would break all animations in all browsers that don't emulate WebKit.

**Comment by pornel** [comment]
the names of variables are not clear though, `transformPrefix` should be "JSTransformProperty" and `transformProperty` should be `CSSTransformProperty`.

**Comment by Jenselme** [comment]
> Setting willChange informs the browser that the element will animate soon, so it should be using an accelerated layer. Without it you would have a delay/jerky animation when it starts moving.

OK. Maybe the detection of FF can be added then? With `'MozTransform' in testElement.style` we can detect if we are on FF and then we can set `transformProperty` to `"-moz-transform"` which solves our problem as well.

Do you want me to work on a patch for that?

**Comment by pornel** [comment]
Firefox has unprefixed `transform` in 2012 in v16. I don't think there's a need to support versions _that_ old.

**Comment by Jenselme** [comment]
> Firefox has unprefixed transform in 2012 in v16.

Yet on FF 44, `transformProperty` must be either an empty string or `-moz-transform` for you bug to be fixed. Don't ask me why thought.

**Comment by pornel** [comment]
That's weird. I've checked, and FF (v47) emulates webkit properties, so the unprefixed empty-string `transformProperty` *is not even used*. 

I've switched the logic around to prefer unprefixed now. 

Perhaps `willChange` exposes a browser bug. Promoting element to a layer could mess with z-index. However, checkboxes and select elements work on my demo page, so I can't reproduce the problem you're reporting.

**Comment by Jenselme** [comment]
> However, checkboxes and select elements work on my demo page, so I can't reproduce the problem you're reporting. 

I think that part of the problem is that on non webkit browser, the `input` is actually a `span` so it can be styled correctly. However, it is a `span` on IE and everything works fine.

**Comment by pornel** [comment]
Sorry, I don't understand. Are you saying you're using something like `<span onclick>` instead of `<input type=checkbox>`?

**Comment by Jenselme** [comment]
> Are you saying you're using something like <span onclick> instead of <input type=checkbox>?

Yes

**Comment by pornel** [comment]
In that case, try disabling swipe-drag on the span:

```
ol.addEventListener('slip:beforeswipe', function(e){
// change that to detect your <span>
        if (e.target.nodeName == 'INPUT' || /demo-no-swipe/.test(e.target.className)) {
            e.preventDefault();
        }
    }, false);
```

**Comment by Jenselme** [comment]
Just tried that. But the `e.preventDefault()` seems to prevent the click to be taken into account. So the checkbox doesn't work.

**Comment by pornel** [comment]
preventDefault is for the custom event, not the click.

You may also want to prevent `slip:beforereorder` to stop span from being used for dragging up/down.

**Comment by Jenselme** [comment]
We finally decided to remove `willChange` in SlipJS to solve our problem.

Anyway, thanks for your help and you awesome lib!
