### ISSUE TITLE
Destroy Slip object

### ISSUE THREAD

**Issue by Garito** [pornel/slip#77]
Hi!
I have a list that you can reorder if a button is pressed
When that happend I create the slip object and set the slip:beforereorder and the slip:reorder events in the container and so on
It works as expected

Now I need to deactivate this feature if the user clicks the button again

How can I do so? Is there a destroy mechanism or something

Thanks!

**Comment by pornel** [comment]
There's a [detach](https://github.com/pornel/slip/blob/f0c21539ef1ee63f7fcc2734e391e6ff021ddb61/slip.js#L533) method. Alternatively, you could use `preventDefault()` on slip's events to prevent it from taking actions.

**Comment by Garito** [comment]
I read the attach and detach methods and I wonder why attach sets accesibility attributes and the tabindex but the detach doesn't remove them

In fact if I remove them manually, the styles are not setted anymore

Must I considere this behaviour a bug or a normal one? (I think more in the 1st one, sorry :P)
In my opinion, the library will be better if no trace are left after using it, don't you think so?
Must to be the developer's call to use this attributes or not after using the library

What do you think?

**Comment by carter-thaxton** [comment]
It's probably a bug.  Want to fix it, and send a pull request?

Though I love this library, it has needed quite a few fixes to be really ready to use.  Pull requests are the way to improve it...  Thanks.

**Comment by francoismassart** [comment]
It looks like the accessibility attributes are removed by the [detach](https://github.com/pornel/slip/blob/master/slip.js#L537) method...
Maybe this issue should be marked as resolved ?

See this commit: https://github.com/pornel/slip/commit/2cdb693e1c38191843ea5d8f9f0002bd574cb7d6

**Comment by carter-thaxton** [comment]
Agreed.  Looks like we simply didn't close the issue.
