### ISSUE TITLE
Get Array of all data

### ISSUE THREAD

**Issue by lbphond** [pornel/slip#86]
Hi, a (simple) last question:
how can I get the array of the data. I know you can get the spliceIndex if you move an item, but if I want to click another item. I'd like to get the whole array, in place of only the item what I'm moving.

Thanks!

**Comment by pornel** [comment]
This library doesn't work the way you think. It doesn't manage any data at all. You use it to display your data. You're supposed to have the data in the first place.

**Comment by lbphond** [comment]
I got the data, but the only thing I need is to put the data out. I saw the data is saved in an array, but I really don't know how to get the array.

**Comment by pornel** [comment]
The library does not hold the data. There is no data in slip. The example I've shown you was for your array of your data, that is never given to or taken from the library.
